### ISSUE TITLE
Avi records YouTube playlist lightning demo, shares publicly

### ISSUE THREAD

**Issue by avidrucker** [knowledge-for-good/knowledgeforgood#107]
Capturing work started in issue #37 and continuing in #108

- [ ] Avi selects several YouTube playlists to share [in-progress]
- [ ] Avi writes a short description of each playlist  [in-progress]
- [ ] Avi records lightning demo
    - [ ] Avi shares lightning demo via YouTube
