### ISSUE TITLE
Project Epic: Find the heart of 3D Knowledge Printer

### ISSUE THREAD

**Issue by avidrucker** [knowledge-for-good/knowledgeforgood#16]
- [ ] Maintainers link other GitHub issues to this "epic" issue to stay organized
- [ ] Avi adds some context & clarity to what he means by "finding the heart"
- [ ] Maintainers brainstorm what their purpose with KFG is, and...
- [ ] ... what they want KFG's mission to be

**Comment by avidrucker** [comment]
I enjoyed reading your stream of consciousness notes @seekanddefine

**Comment by avidrucker** [comment]
My takeaways were:
1. Chunking / micro-tasking allows for consistent steps forward
2. "Improve the project"
3. The project IS the "SSoT"
4. Compensation for a wide range of results/outcomes, but no compensation for "butts in seats"

**Comment by seekanddefine** [comment]
@avidrucker Could we chat about this one during our meeting tonight?

**Comment by seekanddefine** [comment]
Reopening to look at the mission of KFG as we invite our new collaborator to participate.
