### ISSUE TITLE
Avi does a Datomic and Datalog 30 Day Challenge

### ISSUE THREAD

**Issue by avidrucker** [knowledge-for-good/knowledgeforgood#179]
Context: Similar to Avi's 30 Days of Clojure Koans Challenge

Rationale: I need to understand Datomic and Datalog on a deeper level, and increase my skill set (repertoire) accuracy (quality) and fluency (speed).

- [ ] Look up resources for input research
- [ ] Create a test journal to make sure you have runway
- [ ] Build up two to three days worth of content )in case of a sick day
- [ ] Schedule time each day for focused study & journal creation
