### ISSUE TITLE
Plan, deliver, record, and share Liberating Structures workshop

### ISSUE THREAD

**Issue by avidrucker** [knowledge-for-good/knowledgeforgood#182]
- [ ] Conduct research for Liberating Structures workshop
- [ ] Craft the workshop experience
- [ ] Craft the workshop Miro board
- [ ] Promote the event and invite people
- [ ] Facilitate the event while recording
- [ ] Prepare the video file for upload
- [ ] Upload the video & share back here
- [ ] Share rationale here for "why hold a workshop on Liberating Structures?"
