### ISSUE TITLE
KFG Conducts 1 week Clojure workshop

### ISSUE THREAD

**Issue by avidrucker** [knowledge-for-good/knowledgeforgood#188]
- [ ] Create syllabus & course materials
- [ ] Invite people you think might be interested
- [ ] Conduct & record the workshops
- [ ] Upload workshop videos to YouTube channel
- [ ] Upload workshop materials to GitHub
    - [ ] Nextjournal notebooks
    - [ ] Coggle mindmaps
- [ ] Invite / Request feedback from participants, likes, dislikes, suggestions for improvement
