### ISSUE TITLE
Design logo for KFG

### ISSUE THREAD

**Issue by avidrucker** [knowledge-for-good/knowledgeforgood#257]
- [ ] Generate a few placeholder logos for free to use temporarily
- [ ] Brainstorm / Thumbnail first draft
- [ ] Get approval from all KFG members
- [ ] Refine first draft into second draft
- [ ] Get second approval from all KFG members
- [ ] Share high resolution logo to our email addresses for convenient use
    - [ ] Post to our business website
    - [ ] Post to our Linkedin page
    - [ ] Post to our GitHub org
- [ ] Share low resolution logo for usage in digital letterhead
    - [ ] Put into our work email signatures
    - [ ] Put into GitHub for our business avatar
    - [ ] Put into Linkedin as our business avatar
