### ISSUE TITLE
Create & share acro yoga skills map

### ISSUE THREAD

**Issue by avidrucker** [knowledge-for-good/knowledgeforgood#281]
https://www.figma.com/file/lOcQ03S2EozzDuE5wgPXDY/Acro-Yoga-Skills-Map?node-id=0%3A1

- [x] #282
- [ ] Convert paper sketch to shareable digital artifact
- [ ] Do research online to find more skills
- [ ] Get feedback from people on content, spelling, connections & also comments / questions / suggestions
- [ ] Continue to refine and improve
- [ ] Share with the world via social media / Reddit / Linkedin / emailing to friends & family
