### ISSUE TITLE
Members invite non-members to further discussions

### ISSUE THREAD

**Issue by avidrucker** [knowledge-for-good/knowledgeforgood#40]
- [x] VK Business Analyst ( childhood friend of @avidrucker ) **`[done]`**
    - [ ] Log notes & leave link here to notes 
- [ ] DP Computational Linguistics PhD ( college friend of @avidrucker )
- [x] S Psych Major & Startup Founder in RVA ( friend of @avidrucker ) **`[done once, now reoccurring]`**
    - [ ] Log notes & leave link here to notes
- [x] S Software Engineer in Ohio ( friend of @avidrucker )
    - [ ] Log notes & leave link here to notes
- [ ] AW Educational PhD ( friend of @avidrucker )
- [ ] J Educational Success Research ( friend of @seekanddefine )
- [ ] J & T ( family of @seekanddefine )
- [x] Mihai **`[done]`**
    - [ ] Log notes & leave link here to notes
- [x] DF Software Dev (friend of @avidrucker )
    - [ ] Log notes & leave link here to notes
- [ ] J Entrepreneur ( childhood friend of @avidrucker )
