### ISSUE TITLE
Update Knowledge for Good Organization Profile on Github.

### ISSUE THREAD

**Issue by seekanddefine** [knowledge-for-good/knowledgeforgood#45]
[Organization Profile](https://github.com/organizations/knowledge-for-good/settings/profile)

- [x] Display Name: Knowledge For Good (KFG) 
- This is a good name and it works, but it is a name used by other companies/websites already. 
- Here is a [Coggle brainstorm of additional names](https://coggle.it/diagram/YNvRhXMy-XF1eQ-U/t/name-brainstorming/46106496fe0c9b83087370fe60ecf247b8ce844d8c722241cd1c0adce45681ce).
- [x]  Email: seekanddefine@gmail.com
-  A placeholder until something better. 
-  Do we have a reason to create a knowledgeforgood@email?
- [x] Description: *WIP* Knowledge for Good builds tools and community to support all learners pursuing knowledge for the good of themselves and others. 
- [x] URL: ?
- [x] Twitter: @seekanddefine @avidrucker 
- [x] Location: US
- [x] Gravatar email: No idea what this is for
- [x] Sponsors update email: Not sure what this is either.
- [ ] Upload a new profile picture
- [ ] Add a website address for KFG

**Comment by avidrucker** [comment]
> TIL: Gravatar email: https://www.wpbeginner.com/beginners-guide/what-is-gravatar-and-why-you-should-start-using-it-right-away/#:~:text=Gravatar%20stands%20for%20Globally%20Recognized%20Avatar.&text=When%20a%20user%20leaves%20a,out%20the%20world%20wide%20web.
> Recommended action:
> 
> * [x]  Linnea reads the highlighted text

Reflection: I believe this request asked more work of you than I would have liked to. In the future, I would like to copy paste quotes here, with a link to the original, instead of suggesting that you dig around in an article for individual quotes.
