### ISSUE TITLE
Create checklist for video recording, publishing

### ISSUE THREAD

**Issue by avidrucker** [knowledge-for-good/knowledgeforgood#90]
@avidrucker What are you suggestions?

1.  Determine at the beginning of meeting who will record.
2.  Determine how notes will be saved. Default to saving in a source that doesn't disappear (meeting chat disappears).
3.  Record video
    1.  What program?
        1.  **OBS-Free and Opensource**
        2.  Zoom-Free options
        3.  Loom-Free options
        4.  Wondershare DemoCreator
4.  Save video
    1.  What is a good way to organize videos?
    2.  What is a good way to store videos?
5.  Upload to Youtube
    1.  What account do we use to upload to youtube?

_Originally posted by @seekanddefine in https://github.com/knowledge-for-good/knowledgeforgood/issues/57#issuecomment-877909264_

**Comment by seekanddefine** [comment]
Updated _WIP_

*   [ ] Who will record?
*    [ ]  How will they record?

*   Linnea uses Google Meet, Wondershare, or Loom

*    [ ]  How will notes be taken?

*   Discuss with group. 

*   [ ] Use Discord instead of meeting chat.
*    [ ]  Save video
*    [ ]  Process video
*    [ ]  Export video
*    [ ]  Upload to Dropbox or Youtube

**Comment by avidrucker** [comment]
[Checklist is up](https://github.com/knowledge-for-good/knowledgeforgood/blob/main/video_recording_process.md), marking as closed for now. Feel free to open a new issue, referencing back to here, to continue improving the checklist.
